### ISSUE TITLE
Do you support behind proxy requests? 

### ISSUE THREAD

**Issue by gkorland** [dudleycarr/ratelimit.js#24]
Do you deal with IPs hidden behind proxy?

e.g.
'x-forwarded-for'
'forwarded-for'
'x-cluster-ip'

See: [extras.fixIP](https://www.npmjs.com/package/express-extras)

**Comment by ScheerMT** [comment]
I had to deal with this same problem. I was using Express and there was a setting called [trust proxy](http://expressjs.com/en/guide/behind-proxies.html) which you can read up on at the bottom of the page i linked. 

If you aren't using Express it goes on to say,

> "The trust proxy setting is implemented using the [proxy-addr](https://www.npmjs.com/package/proxy-addr) package. For more information, see its documentation."

**NOTE:** Be sure you trust the proxy's value it returns because this header could easily be spoofed.

**Comment by joshgummersall** [comment]
Trust proxy mode is absolutely the way to go. Nothing to add @ScheerMT mentioned everything I would have mentioned.
