### ISSUE TITLE
Clarification on some options in the examples

### ISSUE THREAD

**Issue by mmiller42** [dudleycarr/ratelimit.js#25]
Sorry, I hope these aren't dumb questions, but I was hoping to maybe get a little bit of elaboration on the documentation.
- What is the `precision` option showed in the example?
- Does `extractIps` simply serve as a method for uniquely identifying the client? I'd like to suggest a more generic name for this option if that is the case, then, like `identifyClient`. After all, this could be a good place to return something other than IP addresses, like maybe an API key sent in the request header (rate-limiting free API keys is a common practice) or a user's session ID -- all in case of an attacker switching proxies to bypass the limiter.
- What does the `weight` option do?

**Comment by joshgummersall** [comment]
The weight and precision parameters are discussed in the blog post linked in the README, [that resource is here](http://www.dr-josiah.com/2014/11/introduction-to-rate-limiting-with_26.html).

The weight parameter allows you to specify a variable "cost" per request, which essentially acts as a multiplier for each request (instead of a request costing 1 limit point it can cost 1 \* multiplier limit points). The limit point explanation might sound a bit strange, but I think it's a simple way to think about it.

The precision argument is discussed at length in the "Sliding Windows" section of the article linked above, so I would highly recommend reading that in better detail.

Your suggestion of renaming `extractIps` is not a bad idea at all, and in fact as I quickly browsed through the first article mentioned in the readme, that is how the author named the function. We will likely make that change soon.

**Comment by mmiller42** [comment]
Thanks! I should've looked into that article first. This actually adds quite a bit of neat functionality, especially the sliding windows.

So how is `precision` represented?

```
{interval: 3600, limit: 1000, precision: 10000}
```

3600 I assume is a value in seconds (not milliseconds); but then, is precision represented in milliseconds (i.e. 10-seconds)?

Thanks!

**Comment by joshgummersall** [comment]
Both the `interval` and `precision` are both specified in seconds. The number of buckets you have ends up being `interval / precision`, with the `precision` value defaulting to the `interval` value if not specified. That means the default behavior is an interval of size `n` with a single bucket.

**Comment by mmiller42** [comment]
Sorry, I guess I'm just confused as to the example code in the readme then. That would be 0.36 buckets (`interval / precision`). The quotient should be >= 1 to make sense, right? (And be an integer.)

**Comment by joshgummersall** [comment]
I didn't even realize that was the case - yes it is a bit strange. Intuitively it should be an integer and greater than 1 so I'm not sure why that example is written as such. I'll certainly fix that as well! Thanks for pointing it out.

**Comment by mmiller42** [comment]
Okay cool, just wanted to make sure I understood everything correctly. This is a really awesome package by the way, and will assist greatly with helping to protect some intensive operations on a distributed app. Thanks a lot for creating this guys!

**Comment by joshgummersall** [comment]
Glad you find it useful! I'll keep this issue open to track the `extractIps` rename and updating the README. Thanks again!

**Comment by joshgummersall** [comment]
Actually - @mmiller42 I created two separate issues to track those things, so I'll go ahead and close this issue. It's been linked to in the other issues.
