### ISSUE TITLE
Multi Tenant use cases

### ISSUE THREAD

**Issue by KarthikShanmugasundaram** [dudleycarr/ratelimit.js#33]
I request support for multi tenant use cses.

Rate limit using clientId. Each client id has different set of rate limiting. For example,
1. client id one:
   1min -> 100 requests
   1 hour -> 1K requests
   1day --> 10K requests
2. client id two:
   1min -> 1k requests
   1 hour -> 25K requests
   1day -> 200K requests

There could be atleast 50 client ids for the distribute application. The redis also clustered.

Questions:
Currently implementation support the scale of 10M requests per day?
Redis clustering - will there be any issues? Please clarify

Thank you..

**Comment by joshgummersall** [comment]
To achieve the client ID based rate limiting given the current codebase I would suggest adding a middleware to select a Ratelimit instance/middleware instance to perform rate limiting. It sounds like you are trying to limit when Service A calls Service B differently than when Service C calls Service B, is that right? In that case you could do something like:

``` js
var ServiceLimiters = {
  ServiceA: {
    toServiceB: new Ratelimit()...
  },
  ServiceC: {
    toServiceB: new Ratelimit()...
  }
};

var middleware = function(req, res, next) {
  return new ExpressMiddleware(ServiceLimiters[req.source][req.dest])(req, res, next);
}
```

Obviously a very rough outline above, but that should suffice. Given that the limiters are specific based on the service alone (i.e. the source IP of the request is not important) you would use a function like:

``` js
var extractIdentifiers = function(req) {
  return 1;
}
```

since every request from a service to another service should be treated the same.

As far as Redis clustering, that is not something I've tested with. Assuming a Redis cluster provides the same consistency a single Redis instance provides (i.e. serialized writes) I don't imagine there would be any problems with functionality. The benefit of the structure above is that the amount of data you have stored in Redis is a function of the number of unique identifiers and prefixes (each RateLimit instance would need a separate prefix, and the extractIdentifiers functions should only return 1 value) so your data set will be quite small in size. Perhaps just using a Redis master-slave configuration would suffice (so you have failover protection if the master crashes), but that's up to you to test and profile.
